spring:

  mvc:
    hiddenmethod:
      filter:
        enabled=true:
  messages:
    encoding: UTF-8

  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
  sql:
    init:
      mode: always


logging:
  level:
    ROOT: ERROR